### ISSUE TITLE
Path issue?

### ISSUE THREAD

**Issue by winnerawan** [mvsantos013/laravel-api-boilerplate#1]
I use macbook, got this exception when:
#### 1. 
>composer install
```
ErrorException  : scandir(/Users/mbp/Sites/service/app/Modules):
failed to open dir: No such file or directory
```
theres no Modules directory in app, so when i created the directory and run composer install again, no exception
#### 2
>php artisan scaffold:entity Equipment --module=data
```
ErrorException  : copy(/Users/mbp/Sites/service/app\Console\Commands\ScaffoldEntity\
Model.stub): failed to open stream: No such file or directory
```

```
Exception trace:

  1   copy("/Users/mbp/Sites/service/app\Console\Commands\ScaffoldEntity\Model.stub", "
/Users/mbp/Sites/service/app\Modules\Data\Models\Equipment.php")
      /Users/mbp/Sites/sigi-service/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:239

  2   Illuminate\Filesystem\Filesystem::copy("/Users/mbp/Sites/service/app\Console\Commands\ScaffoldEntity\Model.stub", "/Users/mbp/Sites/service/app\Modules\Data\Models\Equipment.php")
      /Users/mbp/Sites/service/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:239
```
and generate app\Modules\Data\Models\ in root directory

**Comment by mvsantos013** [comment]
I fixed the error related to the missing folder.
I didn't receive the second one, it's probably related to the OS/path, I'll fix that soon. Thanks for the feedback.

**Comment by mvsantos013** [comment]
Alright I think I have fixed it, I can't test it since I only have windows. I'll be adding more instructions soon.

**Comment by winnerawan** [comment]
ill check it
